### ISSUE TITLE
No highlighting

### ISSUE THREAD

**Issue by Pixdigit** [JustusAdam/language-haskell#213]
Until today I had syntax highlighting worked (with 3.6.0). Though as I started VSCode just now, I no longer have Haskell syntax highlighting. When I go back to 3.3.0 the highlighting works again.

I don't know where information may be stored that would help you debug this issue, so if you need any, tell me where and what.

**Comment by bratkartoff** [comment]
I'm having the same issue and found this in the log:
```
[2022-04-28 20:04:21.295] [renderer1] [error] Unable to load and parse grammar for scope source.haskell from file:///home/hal/.vscode-oss/extensions/justusadam.language-haskell-3.6.0/syntaxes/haskell.json {"logTelemetry":false,"fileOperationResult":1,"options":{"preferUnbuffered":true}}
[2022-04-28 20:08:25.551] [renderer1] [error] Unable to load and parse grammar for scope text.tex.latex.haskell from file:///home/hal/.vscode-oss/extensions/justusadam.language-haskell-3.6.0/syntaxes/literateHaskell.json {"logTelemetry":false,"fileOperationResult":1,"options":{"preferUnbuffered":true}}
[2022-04-28 20:08:25.564] [renderer1] [error] Unable to load and parse grammar for scope source.cabal from file:///home/hal/.vscode-oss/extensions/justusadam.language-haskell-3.6.0/syntaxes/cabal.json {"logTelemetry":false,"fileOperationResult":1,"options":{"preferUnbuffered":true}}
```
The files exist in in `~/.vscode-oss/extensions/justusadam.language-haskell-3.3.0/syntaxes`,
but not in `~/.vscode-oss/extensions/justusadam.language-haskell-3.6.0/syntaxes`

**Comment by JustusAdam** [comment]
Are you using open-vsx?

**Comment by Pixdigit** [comment]
I use vs-codium which apparently that uses open-vsx.

**Comment by JustusAdam** [comment]
Yeah there were some issues with the open-vsx upload. It should be fixed now though.

**Comment by ma77hiaz** [comment]
A also use vs-codium (1.66.2) and I still have the issue.
Extensions:
justusadam.language-haskell version 3.6.0
haskell.haskell version 2.2.0

```
[2022-05-05 08:40:29.447] [renderer1] [error] Unable to load and parse grammar for scope source.haskell from file:///Users/matthiashersche/.vscode-oss/extensions/justusadam.language-haskell-3.6.0/syntaxes/haskell.json {"logTelemetry":false,"fileOperationResult":1,"options":{"preferUnbuffered":true}}
[2022-05-05 08:40:38.963] [renderer1] [error] Unable to load and parse grammar for scope text.tex.latex.haskell from file:///Users/matthiashersche/.vscode-oss/extensions/justusadam.language-haskell-3.6.0/syntaxes/literateHaskell.json {"logTelemetry":false,"fileOperationResult":1,"options":{"preferUnbuffered":true}}
[2022-05-05 08:40:38.965] [renderer1] [error] Unable to load and parse grammar for scope source.cabal from file:///Users/matthiashersche/.vscode-oss/extensions/justusadam.language-haskell-3.6.0/syntaxes/cabal.json {"logTelemetry":false,"fileOperationResult":1,"options":{"preferUnbuffered":true}}
```

All the files in the specified directory have the prefix "codeblock":

```
matthiashersche@Mases-MacBook-Pro syntaxes % ls -l
total 40
-rw-r--r--  1 matthiashersche  staff  445 May  5 08:52 C2Hs.json
-rw-r--r--  1 matthiashersche  staff  487 May  5 08:52 Hsc2Hs.json
-rw-r--r--@ 1 matthiashersche  staff  806 May  5 08:52 codeblock-cabal.json
-rw-r--r--  1 matthiashersche  staff  821 May  5 08:52 codeblock-haskell.json
-rw-r--r--  1 matthiashersche  staff  852 May  5 08:52 codeblock-literate-haskell.json
```

**Comment by TheOddler** [comment]
I have the problem still too. Also using vs-codium (1.66.2).

Reverting the addon to version 3.3.0 solves the problem though.

**Comment by JustusAdam** [comment]
The people who do the open-vsx upload were addressing this issue in open-vsx/publish-extensions#583. I don't know why you are getting this error still, mostly because I am not familiar with the infrastructure and processes of open-vsx. Maybe ask the people in that PR when you can expect the fix to show up for you.

**Comment by re-xyr** [comment]
Hi all, the reason why it is still the broken version was because the build timed out... apparently building some documentation required installing a whole Haskell toolchain, which I overlooked.

@JustusAdam Just confirming, is it that `make grammars` is all that's needed to generate files necessary for the extension to work?
